export const TAG_DATA = 'TAG_DATA'
export const TAG_CHANGE = 'TAG_CHANGE'

export const TAGS_DATA = 'TAGS_DATA'
export const TAGS_SAVE = 'TAGS_SAVE'
export const TAGS_LOAD = 'TAGS_LOAD'
export const TAGS_CHANGE = 'TAGS_CHANGE'
export const TAGS_INSERT = 'TAGS_INSERT'
export const TAGS_DELETE = 'TAGS_DELETE'
export const TAGS_UPDATE = 'TAGS_UPDATE'
